### ISSUE TITLE
Pre-launch checklist

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/ecosystem-directory#22]
Using this issue as a holding pen for pre-launch items — we can split out into separate issues later as need be.

- [x] Make repo public
- [x] Once repo public, turn on "automatically delete head branches" in [settings](https://github.com/ipfs/ecosystem-directory/settings) to keep branches tidy
- [x] Once repo public, protect `main` and `develop` branches (can't currently do this on private repos) to keep from automatically deleting those when they're head branches
- [x] (not actually done, but being tracked in https://github.com/ipfs/ipfs-website/pull/71) Update CTA link on ipfs.io for "explore the ecosystem"
- [x] Add standard issue templates
- [x] Connect `main` branch to Fleek
- [x] Configure DNS (`cname` for `ecosystem.ipfs.io.`) to route to Fleek
- [x] Test Fleek build to `main`
- [x] Add link (or embeddable if complete) to ipfs.io (in https://github.com/ipfs/ipfs-website/pull/71)
- [x] Add link to https://ipfs.io/media (in https://github.com/ipfs/ipfs-website/pull/71)
- [x] Add link to https://docs.ipfs.io/welcome-builders/
- [ ] Regression test of all features
- [x] Ensure analytics (`Countly`) is configured on production branch (`main`)
- [x] Test analytics
- [ ] Test SEO indexability
- [x] ~~Add to Google Search Console~~ (using ipfs.io domain as a whole already, so this isn't needed)
- [ ] Consider redirect of old raster URL to something that will generate raster on demand
