### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by 2color** [ipfs/ecosystem-directory#251]
## TODO

- [ ] Clean up the README 
- [ ] Update instructions on adding/submitting  projects
- [ ] Clarify the relationship between this and awesome-ipfs
